### ISSUE TITLE
pod search error.

### ISSUE THREAD

**Issue by wqEsc** [SDWebImage/SDWebImageFLPlugin#1]
pod search SDWebImageFLPlugin 
[!] Unable to find a pod with name, author, summary, or description matching `SDWebImageFLPlugin`

**Comment by dreampiggy** [comment]
@wqEsc Hi. Are you using `SDWebImage 5.0.0-beta` version ? Because we add the dependency to this minimum version, so that if you don't specify it, the Cocoapods will not install it because of depedency failure.

You need to use like this:

```ruby
pod 'SDWebImage', '5.0.0-beta'
pod 'SDWebImageFLPlugin', '~> 0.1.0'
```

Don't forget to run `pod repo update`, or using `pod install --repo-update` to update the Spec source.

I also check the pod trunk source, it's actually already there:

```bash
➜ pod trunk info SDWebImageFLPlugin

SDWebImageFLPlugin
    - Versions:
      - 0.1.0 (2018-07-19 12:47:03 UTC)
    - Owners:
      - DreamPiggy <lizhuoli1126@126.com>
```

**Comment by wqEsc** [comment]
@dreampiggy  After update pod, it's ok now. Thanks.
